version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: oBImp4Z92nR3SDA
      MYSQL_DB: doctor
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: oBImp4Z92nR3SDA
      MYSQL_DATABASE: doctor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
